version: "3.8"
services:
  app:
    container_name:  ${DOCKER_IMAGE}-container
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    build: .
    image: ${DOCKER_IMAGE}
    volumes:
      - .:/_projects/${PROJECT}
    command: bash -c './scripts/launch.sh && yarn dev'
