version: "3.8"
services:
  app:
    container_name: reactgpt-container
    build: .
    image: reactgpt
    ports:
      - "7000:7000"
    # network_mode: host
    volumes:
      - .:/_projects/ReactGpt
    # networks:
    #   - gpt
    command: npm run dev
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
# networks:
#   gpt:
#     name: gpt
