version: "3.8"
services:
  app:
    container_name: reactgpt-container
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    build: .
    image: reactgpt
    volumes:
      - .:/_projects/ReactGpt
    # entrypoint:
    #   - chmod +x ./scripts/launch.sh
    command: >
      bash -c "chmod +x ./scripts/launch.sh &&
               exec yarn dev"
      # sh -c "chmod +x ./scripts/launch.sh" &&
      # - "/bin/sh"
      # - "-c"
      # - "./scripts/launch.sh"
      # - yarn dev
