version: "3.8"
services:
  app:
    container_name: reactgpt-container
    ports:
      - "${VITE_PORT}:${VITE_PORT}"
    build: .
    image: reactgpt
    volumes:
      - .:/_projects/ReactGpt
    command:  "ls -la ./scripts"
      # - "/bin/sh"
      # - "-c"
      # - "./scripts/launch.sh"
      # - yarn dev
