const { VITE_API_GPT, VITE_API_HOST, VITE_API_PORT, VITE_PORT, BASE_URL, MODE } =
  import.meta.env;

export const CONSTANTS = {
  BASE_URL,
  MODE,
  API_PORT: VITE_API_PORT,
  API_HOST: VITE_API_HOST,
  API_GPT_ENDPOINT: VITE_API_GPT,
  API_GPT_URL: `${VITE_API_HOST}:${VITE_API_PORT}${VITE_API_GPT}`,
  APP_PORT: VITE_PORT,
};
